version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres_cardapio_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: clientes_cardapio_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: fastapi_cardapio_app
    restart: always
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://postgres:senha_segura@db:5432/clientes_cardapio_db
    depends_on:
      - db
volumes:
  pgdata:
